### ISSUE TITLE
CPUweight.py has lots of bugs

### ISSUE THREAD

**Issue by philippeller** [IceCubeOpenSource/pisa#416]
there are at least two bugs (or at least differences) in `CPUweight.py`

One was just found by tom: the `nue_numu_ratio` is not being applied because the wrong array is being propagated:

```
new_nue_flux, new_numu_flux
```
and similar quantities are calculated but then simply ignored.

One more bug was found by me after tom found the first: line 210+ is different:

 ``` 
 if kNuBar < 0:
            return np.maximum(
                d0a,
                d1a/(1.0+(1.0 - nu_nubar)*modfactor)
            )
```

which is not the same as GPUweight:

 ```      
if (kNuBar < 0){
            //return 1./(1+(1-nu_nubar)*modfactor);
            return max(0.,1./(1+0.5*modfactor));
        }
```

**Comment by jllanfranchi** [comment]
File has been removed
