### ISSUE TITLE
SmartArray deprecation in numba 0.44, removal in 0.45

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#536]
See http://numba.pydata.org/numba-doc/latest/cuda/memory.html#smartarrays-deprecated-since-version-0-44

We need to think of a way forward. We will also need to deal with Python 2.x deprecations, so moving to Python 3 (3.6 or higher?) simultaneously might be advisable since numpy 1.17, which is only supported on Python 3, introduces an API functionality whereby numpy calls operate on cupy or numpy arrays transparently (cupy seems to be the increasingly predominant GPU array library of choice). Numba can work with cupy arrays on GPU and numpy arrays on CPU.

These are only initial thoughts, a lot of legwork will probably be necessary to get it all working. First step might be to get PISA working on Python 3, commit all of those changes, then we can deal with the SmartArray deprecation.

An obvious workaround in the meantime would be to pin Numba version at <= 0.44, but surely there will be improvements beyond 0.44 that we'll want at some point, so that can be a temporary measure.

**Comment by philippeller** [comment]
Will not be needed in pisa4 anymore
