### ISSUE TITLE
Duplicate `mcllh_eff` functions defined in stats.py

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#547]
Commit 75b64d0278cf1ee892078c42c10a8643aa757d35 renamed `thorsten_llh` as `mcllh_mean` and renamed `say_llh` as `mcllh_eff` in `map.py` but renamed both `thorsten_llh` and `say_llh` to `mcllh_eff` in `stats.py`.

See diff here: https://github.com/IceCubeOpenSource/pisa/commit/75b64d0278cf1ee892078c42c10a8643aa757d35#diff-1334536ceecd695ac38b5eaa6d586df2

Blame appears to lie one @austinschneider and/or @philippeller so I'm assigning this to you two this issue to sort out.

**Comment by austinschneider** [comment]
Pull request #548 should fix this issue.
