### ISSUE TITLE
py3 bug in `MapSet.metric_total`

### ISSUE THREAD

**Issue by ts4051** [IceCubeOpenSource/pisa#551]
The following error is seen when running scans in the `master` branch following the update to py3:

```
TypeError: unsupported operand type(s) for +: 'odict_values' and 'float'
```

The underlying cause comes from the `MapSet.metric_total`, and is due to the fact that `OrderedDict.values()` returns a `view` in python3, rather than a `list` in python2, and this doesn't play nicely with `numpy.sum()`.

Changing the offending line from 

```
        return np.sum( self.metric_per_map(expected_values, metric).values() )
```

to 

```
        return np.sum( list(self.metric_per_map(expected_values, metric).values()) )
```
fixes the problem.

**Comment by jllanfranchi** [comment]
Fixed with PR #543
