### ISSUE TITLE
Setting DistributionMaker.params causes inconsistency for repeated params

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#566]
Accessing the `params` attr on a `DistributionMaker` collects `params` from each contained `Pipeline`, but if the same `Param` is used in more than one `Pipeline`, the above method only grabs the _first_ one, so changing anything in the returned `ParamSet` leads to inconsistency in this case.

```python
from pisa import ureg
from pisa.core.pipeline import Pipeline
from pisa.core.distribution_maker import DistributionMaker

# I'm using the same config twice just for convenience
p0 = Pipeline("~/src/pisa/pisa_examples/resources/settings/pipeline/example.cfg")
p1 = Pipeline("~/src/pisa/pisa_examples/resources/settings/pipeline/example.cfg")

print(p0.params.livetime)

dm = DistributionMaker([p0, p1])

# this gives you one of each unique param from each pipeline...
all_params = dm.params
print(all_params.livetime)

# so if you set a param in that ParamSet, it doesn't set _all_ params in all contained pipelines.
all_params.livetime = 3 * ureg.common_year
dm.params

# one can still set the params on each pipeline individually and the desired result is what you expect
for pipeline in dm:
    if "livetime" in pipeline.params.names:
        pipeline.params.livetime = 3 * ureg.common_year
        pipeline.params.livetime.fixed = True
```
A possible fix that would be transparent to users and optmizers alike is to make `ParamSet` able to handle multiple instances of the same Param.

Unless this is implemented, `params` should probably not be an attr of `DistributionMaker` at all so it doesn't mislead users (or code interfacing with an optimizer) into thinking the returned object can be manipulated such that consequent changes will be made on all instances of all params in all pipelines.

**Comment by philippeller** [comment]
We could, when a DistributionMaker is instantiated, replace instances of repeated param names with a single param object, so two pipleines would reference the same param.

**Comment by philippeller** [comment]
I now fixed this behaviour in pisa4
