### ISSUE TITLE
Fix dependency versions in setup.py

### ISSUE THREAD

**Issue by atrettin** [IceCubeOpenSource/pisa#569]
Several people were having trouble installing PISA lately because the newest versions of pint and llvm do not play nicely with numba 0.43.1, which we are currently stuck with. We have to fix version numbers in `setup.py` to specific versions known to work, at least until we get un-stuck from numba 0.43.1.

**Comment by jllanfranchi** [comment]
We'll discuss the larger issue of SmartArray elsewhere, but fixing versions is a necessary first step. I'll try a fresh install according to what @ellohfin recommended, run all the unit tests, and then try to get a PR out later today.

**Comment by jllanfranchi** [comment]
Appears fixed in the short term via PR #571
