### ISSUE TITLE
Fix matrix.py unit test

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#570]
* Does the unit test check against anything?
* Make unit test into its own function that is named `test_<something>`, and then this function gets called in the `if __name__ == "__main__":` code block (this makes it compatible with `py.test` unit testing package when someday we convert to using that)
* Make PASS output same as other unit tests in PISA: `<< PASS : test_blah >>`; make it exit with an exception if it fails
* Don't print anything else out, we want to read as little as possible when examining the output of a hundred unit tests

**Comment by atrettin** [comment]
Fixed, see pull request #575 .
