### ISSUE TITLE
Make vectorizer names more self-expanatory

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#573]
I propose the following renaming to make more clear what each function does, trying to follow established Python conventions first and foremost (mostly from https://docs.python.org/3.5/library/operator.html, otherwise https://docs.python.org/3.5/library/math.html or numpy or ...).

The only anti-convention that remains is the operator ordering, which is forced by `numba.guvectorize` to have the final argument (with name `out`) be the one that is assigned to. I write the numpy equivalent to each operation as I understand each gufunc (as currently defined in the code), and proposed update to functionality / arg names. I use `x[:]`, `y[:]`, `z[:]` for (possibly) array-like things and `a` (no square brackets) for a strictly scalar thing. See https://github.com/IceCubeOpenSource/pisa/blob/master/pisa/utils/vectorizer.py

Note that I try to make consistent singular names for strictly scalar arguments and plural names for possibly vector arguments. (There was previously a mixture of the two for either/both.) The only violation of this is `out` (again, that name is fixed by numpy convention).

Orig name | New name | Orig op/args | New op/args
:-- | :-- | :-- | :--
`multiply` | `imul` | `out[:] *= val[:]` | `out[:] *= vals[:]`
`scale` | `mul` | `out[:] = scale[:] * value[:]` | `out[:] = vals0[:] * vals1[:1]`
`multiply_and_scale` | `imul_and_scale` | `out[:] *= scale[:] * value[:]` | `out[:] *= vals[:] * scale`
`divide` | `itruediv` | `out[:] /= val[:]` | `out[:] /= vals[:]`
`set` | `assign` | `out[:] = val[:]` | `out[:] = vals[:]`
`square` | `pow` | `out[:] = val[:]**2` | `out[:] = vals[:]**pwr`
`sqrt` | (unchanged) | `out[:] = sqrt(val[:])` | `out[:] = sqrt(vals[:])`
`replace` | `replace_where_counts_gt` | `out[counts[:] > min_count] = vals[counts[:] > min_count]` | (unchanged)

**Comment by jllanfranchi** [comment]
Thoughts on this from main users' of these functions? @philippeller @ts4051 @atrettin (and anyone else, of course)

**Comment by atrettin** [comment]
I'd be ok with the naming convention, but is there a way to automate the re-factoring of code here? I don't want to have to go through everything to hunt down every instance of these occurring.

**Comment by jllanfranchi** [comment]
I already checked using `rg` in `fridge` and `pisa`, and there aren't that many occurrences of any of these things and they're easy to spot, so it should be easy enough to modify these manually (unless there is some code I'm unware of outside those two repos)

**Comment by jllanfranchi** [comment]
Fixed wtih PR #574
