### ISSUE TITLE
Add NSI unit tests to prob3numba/numba_osc_tests.py

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#599]
Could use one or more sets of values for `mat_pot` that make sense for unit tests so we can make sure that results are at least consistent over time for NSI. (See, e.g., test cases defined here: https://github.com/IceCubeOpenSource/pisa/blob/48bdc371cc230ef4e8a3afa29c1ad58aac606a6c/pisa/stages/osc/prob3numba/numba_osc_tests.py#L107-L128)

That file can be called directly as a script from the command line with the flag `--define-as-ref`, and should be done so running on CPU (we are making CPU the reference) both with PISA_FTYPE=fp32 and PISA_FTYPE=fp64. This should generate the test data files that we can use into the future for whatever test case(s) you come up with, and we can selectively check in just those files you generate for those tests.

**Comment by ellohfin** [comment]
Where to best define the matrices to be tested? For now I just definine them somewhere above TEST_CASES, since some NSI parameters need to be set there.

**Comment by ellohfin** [comment]
The test cases I've been thinking of so far are
1) vacuum like NSI with non-0 epsilon prime
2) std NSI with parameters at something around the best fit values Thomas got from the DRAGON analysis
Any suggestions?

**Comment by jllanfranchi** [comment]
So long as you're setting `mat_pot` (and/or any other argument value), you should be able to define those in `TEST_CASES`. If an arg value isn't defined there, then it is assigned a default value from DEFAULTS ... Or maybe I don't understand what you need to do?

**Comment by ellohfin** [comment]
Right, that's probably the easiest way
