### ISSUE TITLE
Stage configuration arguments are parsed as Quantity

### ISSUE THREAD

**Issue by atrettin** [IceCubeOpenSource/pisa#608]
When a configuration file of a pipeline is parsed, stage initialization arguments not meant for optimization are parsed as quantities with units, even when only a simple number is given. When a config file contains ```seed = 42```, it currently gets ```Quantity(42.0, dimensionless)``` as an argument into its ```__init__``` function, when it should get the number 42 as an integer.

**Comment by jllanfranchi** [comment]
Fixed with PR #609 / commit 8b6d88627e46519b1431effe4626eb0ac0085678
