### ISSUE TITLE
Binning enhancement to facilitate resampling

### ISSUE THREAD

**Issue by atrettin** [IceCubeOpenSource/pisa#619]
I'm currently working on the resampling stage and there are two enhancements to the binning classes that would make it more practical:

1. Rename `is_compat` to `is_downsample` or something to the effect. That would make it clearer what the function is testing for. A stage can just exchange the order of the comparison to check for upsampling compatibility. This also allows for automatic switching between upsampling and downsampling modes in a more generalized resample stage.
2. Make it possible to get bin volumes for bins in log dimensions in "units" of orders of magnitude. In other words, make bins that have the same size visually in a plot have the same volume. The assumption that events are evenly distributed over bins that are being upsampled into makes more sense in log-energy than in energy.

**Comment by jllanfranchi** [comment]
If you read the comments and TODO's in the sourcecode around `is_compat`, you might have gleaned that I originally imagined this would be a function to test whether one could _either_ upsample _or_ downsample from the binning of `self` to the binning of `other`. But that never became a use case, and you are now using it in a test that requires that it return True if one can downsample, and False even if one can upsample. That's obviously a valid thing to want to do, but I agree that either the name needs to change. To make it "grammatical," maybe:
* `can_upsample_to`: can binning of `self` be upsampled to binning of `other`
* `can_downsample_to`: vice versa
* `can_resample_to`: either way

There's further complication in the terminology and the assumptions that we're making in that arbitrarily re-binning of histograms without requiring that the new bin edges are a super-/subset of the source binning shouldn't be terribly difficult and is likely the next step someone will want to make from here. From that point of view, only a check that dimensionality is equivalent is necessary (and maybe one would optionally want to have a flag that checks that no extrapolation is necessary to get from one binning to the other... or that's the default check, and the flag allows for extrapolation).

Maybe this simple kind of dimensionality check, that accommodates arbitrary re-binning, is the kind of thing that we place in `is_compat`.

In fact, now that I'm thinking about it, if you have the logic and/or implementation of upsampling already, then I don't see why (so long as all edges are within the domain of the original binning) you can't implement resampling with arbitrary bin edges. E.g., if you start with binning (in 1d, the bookkeeping gets a bit more hairy in higher dimensions)
```
|______|______|
```
and you want to go to binning
```
 |___|___|___|
```
then you take the union of the two binnings:
```
 |___|_|_|___|
```
 to create an intermediate binning where the contents of each bin are clear how to compute, and then just merge the middle two bins ("selectively downsample") to obtain the desired binning.

If you (we?) could get that working, then all of the `can_*sample_to` functions are unnecessary, we only need the simple version of `is_compat` that checks dimension names, units, and that the output domain is a subset of the input domain.

As to your second point, computing volumes that are equal in the space of the binning is something that definitely makes sense, and should be relatively easy to implement. I'm not completely happy with the name, but we have `weighted_centers` to describe finding points that are evenly distributed in the space of the binning, how does `weighted_bin_widths` (for `OneDimBinning`) and `weighted_bin_volumes` (for `MultiDimBinning`) sound? Or just `weighted_widths` and `weighted_volumes`?

**Comment by atrettin** [comment]
I agree that the arbitrary resampling via the union of both binnings should be straight forward to implement. I would still want to check whether direct up- or downsampling is possible such that the stage can skip unnecessary steps...

Maybe we can agree to the following test convention:
`can_upsample_to`: Test whether direct upsampling is possible (i.e. only adding edges).
`can_downsample_to`: Test whether direct downsampling is possible (i.e. only removing edges)
`can_resample`: Test whether generalized resampling is possible. This is a weaker condition than the other two tests since it only requires the outermost bin edges to match.

**Comment by jllanfranchi** [comment]
Make `can_resample` `can_resample_to` and I'm good with your proposal. If we do remove the other, we just have to be careful about where else it might be used (hopefully not many places in either PISA or the fridge), or deprecate it, or etc...

**Comment by atrettin** [comment]
Yep, `can_resample_to` is good! I think GitHub can tell us all places where the former `is_compat` function was used, right?

Also, it would be great if you could also implement the union of two binnings if it doesn't already exist! :)

**Comment by jllanfranchi** [comment]
Well, I think the implementation of that might depend on what we're going to do with it. I.e., it seems like creating upsampled binning will probably be used for upsampling, and so it probably makes sense to be done simultaneously with the bookkeeping to identify which old bin index each new bin is generated from. @philippeller do you already have code to do this? It seems like you've already solved the problem, maybe your experience can help out here (and/or maybe we can just start depending on your library and pull from it...)

**Comment by jllanfranchi** [comment]
Also @atrettin, I highly recommend [`rg`](https://github.com/BurntSushi/ripgrep) for a better alternative to `grep -r` for finding text in lots of source code....

**Comment by atrettin** [comment]
This is all done now.
