### ISSUE TITLE
Container linking

### ISSUE THREAD

**Issue by philippeller** [IceCubeOpenSource/pisa#638]
When using the MCEq stage with container linking weird shape differences appear when events are cut to their output reco binning range, as shown by @atrettin:
![image](https://user-images.githubusercontent.com/5046833/93231459-0aa65d80-f779-11ea-84d1-cfedaff7f436.png)

This is not the case without linking or in events mode.

**Comment by philippeller** [comment]
One thing to try:

when accessing items in a linked container, keep track of all items in a list
when unlinking, copy all contents

**Comment by philippeller** [comment]
Turnes out to be a problem in how fluxes were applied. They were applied to linked containers and hence not to the right fluxes

**Comment by atrettin** [comment]
> Turnes out to be a problem in how fluxes were applied. They were applied to linked containers and hence not to the right fluxes

Could you elaborate on that? It seemed to me like the way it was done should be correct, where did the logic go wrong?

**Comment by philippeller** [comment]
I believe here: https://github.com/IceCubeOpenSource/pisa/blob/master/pisa/stages/flux/pi_mceq_barr_red.py#L429

It is applied to the flux in linked mode, however they can have different fluxes for different flavours, if the output from the flux stage is applied in events mode.

I think this problem will naturally disappear in pisa4 🤞
